### ISSUE TITLE
Extra argument to Polytope.add_bounds

### ISSUE THREAD

**Issue by rdeits** [TobiaMarcucci/py-mpc#7]
The box_atlas notebook calls `kinematic_limits.add_bounds(q_b_min, q_b_max, [0,1])`, but it looks like the Polytope class that's on `master` doesn't support that last argument. I assume those are the indices corresponding to the bounds you're adding? 

Do you maybe have local changes to that file that haven't been pushed?

**Comment by TobiaMarcucci** [comment]
Yes, sorry I lost polytope.py in the last push. I've just pushed my local changes. Let me know if it works now!

**Comment by rdeits** [comment]
Yup, seems to be working. Thanks!
